Fix backwards incompatible behavior upgrading from git 2.21 to 2.22
Summary: The new version of git fails to run the `git submodule foreach --recursive git clean -x -d -f -f` command that used to run successfully with git v2.21. This fix works with both git versions.

Test Plan:
Successfully repro the issue on `airports/venue-events-realtime` and this change fixes it on this repo on both git v2.21 and v2.22.

Error used to be:
```
UBER]  error executing command [git submodule foreach --recursive git clean -x -d -f -f] at /Users/jeffs/.dep-cache/pkg/dep/sources/ssh---gitolite@code.uber.internal-infra-boulder.git, err:exit status 128, out: Entering 'jepsen'
error: unknown switch `x'
usage: git submodule--helper foreach [--quiet] [--recursive] [--] <command>

    -q, --quiet           Suppress output of entering each submodule command
    --recursive           Recurse into nested submodules

fatal: run_command returned non-zero status while recursing in the nested submodules of jepsen
```

Reviewers: vit, jeffs

Reviewed By: vit

Tags: #build_platform

Differential Revision: https://code.uberinternal.com/D2946545